database: 'data/rutez_db/rutez.db'
rutez_dir: 'data/rutez_xml/'
corpus: 'data/corpus/lugovoy_corpus.json'
annotation: 'data/annotation/lugovoy_ann.csv'
log_file: 'ex1_logs.csv'
output: 't.csv'

models:
  - 'data/models/ruscorpora_upos_cbow_300_20_2019.zip'

window_size:
  - 12

context_window_size:
  - 3

max_relation_order:
  - 2

threshold:
  - 0

use_bigrams:
  - False
  - True

word_type_mapping:
  INFN: VERB
  PRTF: VERB
  GRND: VERB
  PRTS: VERB
  ADJF: ADJ