database: 'data/rutez_db/rutez_test.db'
rutez_dir: 'data/rutez_xml/'
text: 'data/para.csv'
corpus: 'data/corpus/flt.json'
annotation: 'data/annotation/flt.csv'
log_file: 'ex1_logs.csv'
models:
  - 'data/models/news_upos_skipgram_300_5_2019.zip'
  - 'data/models/ruscorpora_upos_cbow_300_20_2019.zip'
  - 'data/models/tayga_upos_skipgram_300_2_2019.zip'

word_type_mapping:
  INFN: VERB
  PRTF: VERB
  GRND: VERB
  PRTS: VERB
  ADJF: ADJ