database: 'data/rutez_db/rutez.db'
rutez_dir: 'data/rutez_xml/'
corpus: 'data/corpus/aviabasa.json'
log_file: 'ex1_logs.csv'
output: 'result_avia.csv'

models:
  - 'data/models/ruscorpora_upos_cbow_300_20_2019.zip'

window_size:
  - 20

context_window_size:
  - 4


max_relation_order:
  - 2

threshold:
  - 0.5

word_type_mapping:
  INFN: VERB
  PRTF: VERB
  GRND: VERB
  PRTS: VERB
  ADJF: ADJ