url_starter: 'https://news.yandex.ru/'
db_name: 'db.db'
verbose: True
url_list:
    - 'http://news.yandex.ru/world.html'
    - 'http://news.yandex.ru/society.html'
    - 'http://news.yandex.ru/business.html'
    - 'http://news.yandex.ru/sport.html'
    - 'http://news.yandex.ru/football.html'
    - 'http://news.yandex.ru/hockey.html'
    - 'http://news.yandex.ru/basketball.html'
    - 'http://news.yandex.ru/tennis.html'
    - 'http://news.yandex.ru/incident.html'
    - 'http://news.yandex.ru/culture.html'
    - 'http://news.yandex.ru/science.html'
    - 'http://news.yandex.ru/health.html'
    - 'http://news.yandex.ru/computers.html'
    - 'http://news.yandex.ru/internet.html'
    - 'http://news.yandex.ru/games.html'
    - 'http://news.yandex.ru/auto.html'
    - 'http://news.yandex.ru/travels.html'
